[package]
name = "remote-externalities"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "An externalities provided environment that can load itself from remote nodes or cached files"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
env_logger = "0.9"
log = "0.4.17"
serde = "1.0.136"
serde_json = "1.0"
sp-core = { version = "6.0.0", path = "../../../primitives/core" }
sp-io = { version = "6.0.0", path = "../../../primitives/io" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" }
sp-storage = { version = "6.0.0", path = "../../../primitives/storage" }
sp-version = { version = "5.0.0", path = "../../../primitives/version" }
sp-state-machine = { path = "../../../primitives/state-machine" }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
substrate-rpc-client = { path = "../rpc/client" }

frame-support = { version = "4.0.0-dev", optional = true, path = "../../../frame/support" }

[dev-dependencies]
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" }
pallet-elections-phragmen = { version = "5.0.0-dev", path = "../../../frame/elections-phragmen" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[features]
remote-test = ["frame-support"]
