[package]
name = "bags-list"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME bags list"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

# primitives
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "5.0.0", default-features = false, path = "../../../../primitives/std" }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../support" }

macro_magic = "0.3.1"

[features]
default = ["std"]
std = [
	"scale-info/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
    "frame-support/std"
]