[package]
name = "pallet-stake-tracker"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME stake tracker pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }

sp-io = { version = "7.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "5.0.0", default-features = false, path = "../../primitives/std" }
sp-staking = { version = "4.0.0-dev", default-features = false, path = "../../primitives/staking" }

frame-election-provider-support = { default-features = false, path = "../election-provider-support" }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" }

[dev-dependencies]
substrate-test-utils = { version = "4.0.0-dev", path = "../../test-utils" }
sp-tracing = { version = "6.0.0", path = "../../primitives/tracing" }
pallet-staking = { path = "../staking" }
pallet-balances = { path = "../balances" }
pallet-timestamp = { path = "../timestamp" }
sp-npos-elections = { version = "4.0.0-dev", path = "../../primitives/npos-elections" }
pallet-bags-list = { version = "4.0.0-dev", path = "../bags-list" }
frame-election-provider-support = { version = "4.0.0-dev", path = "../election-provider-support" }





[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",

	"frame-support/std",
	"frame-system/std",

	"sp-io/std",
	"sp-staking/std",
	"sp-runtime/std",
	"sp-std/std",

	"frame-election-provider-support/std",

	"frame-benchmarking/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks"
]


try-runtime = ["frame-support/try-runtime"]
