[package]
name = "pallet-migrations"
version = "1.0.0"
description = "FRAME pallet to execute multi-block migrations."
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://substrate.io"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paritytech/substrate"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }
impl-trait-for-tuples = "0.2.2"
log = "0.4.18"
sp-std = { version = "8.0.0", path = "../../primitives/std", default-features = false }
sp-runtime = { version = "24.0.0", path = "../../primitives/runtime", default-features = false }
docify = "0.1.14"

[dev-dependencies]
sp-api = { version = "4.0.0-dev", path = "../../primitives/api", features = [ "std" ] }
sp-tracing = { version = "10.0.0", path = "../../primitives/tracing", features = [ "std" ] }
sp-core = { version = "21.0.0", path = "../../primitives/core", features = [ "std" ] }
sp-version = { version = "22.0.0", path = "../../primitives/version", features = [ "std" ] }
sp-io = { version = "23.0.0", path = "../../primitives/io", features = [ "std" ] }
sp-block-builder = { version = "4.0.0-dev", path = "../../primitives/block-builder", features = [ "std" ] }
pretty_assertions = "1.3.0"
docify = "0.1.14"
frame-executive = { version = "4.0.0-dev", path = "../executive" }

[features]
default = ["std"]

std = ["codec/std", "frame-benchmarking?/std", "frame-support/std", "frame-system/std", "scale-info/std", "sp-std/std", "sp-runtime/std"]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks", "frame-support/runtime-benchmarks", "frame-system/runtime-benchmarks", "sp-runtime/runtime-benchmarks"]

try-runtime = ["frame-support/try-runtime", "sp-runtime/try-runtime"]
