[package]
name = "pallet-migrations"
version = "1.0.0"
description = "FRAME pallet to execute multi-block migrations."
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://substrate.io"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paritytech/substrate"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }
impl-trait-for-tuples = "0.2.2"
log = "0.4.18"
sp-std = { version = "6.0.0", path = "../../primitives/std", default-features = false }

[dev-dependencies]
sp-tracing = { version = "7.0.0", path = "../../primitives/tracing", features = [ "std" ] }
sp-core = { version = "8.0.0", path = "../../primitives/core", features = [ "std" ] }
sp-io = { version = "8.0.0", path = "../../primitives/io", features = [ "std" ] }
sp-runtime = { version = "8.0.0", path = "../../primitives/runtime", features = [ "std" ] }

[features]
default = ["std"]

std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-std/std",
]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks", "frame-support/runtime-benchmarks", "frame-system/runtime-benchmarks"]

try-runtime = ["frame-support/try-runtime"]
