[package]
name = "pallet-stake-tracker-initializer"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME stake tracker initializer submodule"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-staking = { path = "../../staking", default-features = false }
pallet-stake-tracker = { path = "../", default-features = false }
sp-std = { version = "5.0.0", default-features = false, path = "../../../primitives/std" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../primitives/runtime" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../system" }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false, path = "../../election-provider-support" }
log = { version = "0.4.17", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
    "derive",
] }


[features]
default = ["std"]

std = [
    "pallet-staking/std",
    "pallet-stake-tracker/std",
]

try-runtime = [
    "frame-support/try-runtime",
    "pallet-staking/try-runtime",
    "pallet-stake-tracker/try-runtime",
]
