[package]
name = "sub-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.145", features = ["derive"] }

jsonrpsee = { version = "0.15.1", features = ["jsonrpsee-types", "jsonrpsee-http-client", "jsonrpsee-ws-client"] }

sp-core = { version = "6.0.0", path = "../../../primitives/core" }
sp-version = { version = "5.0.0", default-features = false, path = "../../../primitives/version" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../frame/support" }
frame-metadata = { version = "15.0.0", default-features = false, features = ["v14"] }

# Optional for helpers only.
frame-system = { version = "4.0.0-dev", path = "../../../frame/system", optional = true }
pallet-identity = { version = "4.0.0-dev", default-features = false, path = "../../../frame/identity", optional = true }
pallet-balances = { version = "4.0.0-dev", default-features = false, path = "../../../frame/balances", optional = true }
ansi_term = { version = "0.12.1", optional = true }

[dev-dependencies]
async-std = { version = "1.12.0" }
tokio = { version = "1", features = ["full"] }
hex-literal = "0.3.4"
hex = "0.4.3"
frame-system = { version = "4.0.0-dev", path = "../../../frame/system"}
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" }
pallet-balances = { version = "4.0.0-dev", path = "../../../frame/balances" }
pallet-staking = { version = "4.0.0-dev", path = "../../../frame/staking" }
pallet-proxy = { version = "4.0.0-dev", path = "../../../frame/proxy" }

[features]
remote-test-kusama = []
remote-test-polkadot = []
default = []
helpers = [
	"frame-system",
	"pallet-identity",
	"pallet-balances",
	"ansi_term",
]
