[relaychain]
default_image = "docker.io/paritypr/substrate-debug:master"
default_command = "substrate"

chain = "gen-db"
chain_spec_path = "0001-chain-spec.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  #we need at least 3 nodes for warp sync
  [[relaychain.nodes]]
  name = "charlie"
  validator = false
  args = ["--sync full"]

  [[relaychain.nodes]]
  name = "dave"
  validator = false
  ws_port=39047
  args = ["--sync warp"]

