[relaychain]
default_image = "docker.io/parity/substrate:master"
default_command = "/home/miszka/parity/05-zombienet-warp-sync/substrate-wrap.sh"
# dir_snapshot="s3://bucket/0001-test-warp-sync/snapshots/network"

chain = "gen-db"
chain_spec_path = "0001-chain-spec.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  # dir_snapshot="s3://bucket/0001-test-warp-sync/snapshots/bob"

  #we need at least 3 nodes for warp sync
  [[relaychain.nodes]]
  name = "charlie"
  validator = false
  args = ["--sync full"]

  [[relaychain.nodes]]
  name = "dave"
  validator = false
  ws_port=39047
  args = ["--sync warp"]

