[settings]
enable_tracing = false

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
default_command = "substrate"

chain = "gen-db"
chain_spec_path = "0001-chain-spec.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  # see: https://github.com/paritytech/zombienet/issues/578
  # dir_snapshot="s3://bucket/0001-test-warp-sync/snapshots/node-db.tgz"

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  # dir_snapshot="s3://bucket/0001-test-warp-sync/snapshots/node-db.tgz"

  #we need at least 3 nodes for warp sync
  [[relaychain.nodes]]
  name = "charlie"
  validator = false
  # dir_snapshot="s3://bucket/0001-test-warp-sync/snapshots/node-db.tgz"

  [[relaychain.nodes]]
  name = "dave"
  validator = false
  args = ["--sync warp"]
  # port is fixed for local debugging convenience
  ws_port=39047
